name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-php:
    name: Prepare PHP
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image: [ ubuntu-20.04 ]
        php: [ 8.2 ]

    steps:
      - name: Build and prepare PHP cache
        uses: pmmp/setup-php-action@d2510ba2c63846f7aac4ed6e8b6b2346400c9ef0
        with:
          php-version: ${{ matrix.php }}
          install-path: "./bin"
          pm-version-major: 5
  phpstan:
    name: PHPStan Analysis
    needs: build-php
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ ubuntu-20.04 ]
        php: [ 8.2 ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.25.5
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Restore Composer package cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ matrix.php }}-${{ hashFiles('./composer.lock') }}"
          restore-keys: |
            composer-v2-cache-
      - name: Install Composer dependencies
        run: php composer.phar install --prefer-dist --no-interaction

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze src --no-progress --memory-limit=2G
  codestyle:
    name: Code Style checks
    runs-on: ubuntu-20.04
    needs: build-php
    strategy:
      fail-fast: false
      matrix:
        image: [ ubuntu-20.04 ]
        php: [ 8.2 ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.25.5
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Restore Composer package cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ matrix.php }}-${{ hashFiles('./composer.lock') }}"
          restore-keys: |
            composer-v2-cache-

      - name: Install Composer dependencies
        run: php composer.phar install --prefer-dist --no-interaction

      - name: Run PHP-CS-Fixer
        run: php vendor/bin/php-cs-fixer fix --dry-run --diff --ansi
        env:
          PHP_CS_FIXER_IGNORE_ENV: true

  phpunit:
    name: PHPUnit Tests
    needs: build-php
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image: [ ubuntu-20.04 ]
        php: [ 8.2 ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@2.25.5
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer
        run: curl -sS https://getcomposer.org/installer | php

      - name: Restore Composer package cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ matrix.php }}-${{ hashFiles('./composer.lock') }}"
          restore-keys: |
            composer-v2-cache-
      - name: Install Composer dependencies
        run: php composer.phar install --prefer-dist --no-interaction

      - name: Run PHPUnit
        run: php vendor/bin/phpunit --bootstrap vendor/autoload.php tests/